### ISSUE TITLE
Appears placeholder image only.

### ISSUE THREAD

**Issue by Aakash-DD** [mnw007/music_player#1]
Appears placeholder image only all the time.
Where are the songs?

**Comment by mnw007** [comment]
Songs which are present in external memory are displayed. Songs downloaded on third-party apps will not be shown as they are protected.

**Comment by Aakash-DD** [comment]
external memory ? what are you referring?

**Comment by mnw007** [comment]
External storage refers to [(primary](https://developer.android.com/reference/android/provider/MediaStore.Audio.Media)) public storage where apps can read/write data. It should not be confused with  [SD card.](https://developer.android.com/training/data-storage/files)
